class LeafJotsError(Exception): ...


class ParseError(LeafJotsError): ...


class PriceNotFoundError(LeafJotsError): ...


class BalanceError(LeafJotsError): ...


class TaxCalculationError(LeafJotsError): ...


class ExternalServiceError(LeafJotsError): ...


class ValidationError(LeafJotsError): ...
