"""phase5_to_9_complete

Revision ID: 6080bbca93a1
Revises: phase4_001
Create Date: 2026-02-18 12:05:38.005097

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6080bbca93a1'
down_revision: Union[str, Sequence[str], None] = 'phase4_001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('price_cache',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(length=50), nullable=False),
    sa.Column('timestamp', sa.Integer(), nullable=False),
    sa.Column('price_usd', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_price_cache')),
    sa.UniqueConstraint('symbol', 'timestamp', name='uq_price_cache_symbol_timestamp')
    )
    op.create_index(op.f('ix_price_cache_symbol'), 'price_cache', ['symbol'], unique=False)
    op.create_index(op.f('ix_price_cache_timestamp'), 'price_cache', ['timestamp'], unique=False)
    op.create_table('reports',
    sa.Column('entity_id', sa.Uuid(), nullable=False),
    sa.Column('period_start', sa.DateTime(), nullable=False),
    sa.Column('period_end', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=True),
    sa.Column('generated_at', sa.DateTime(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], name=op.f('fk_reports_entity_id_entities')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reports'))
    )
    op.create_table('closed_lots',
    sa.Column('entity_id', sa.Uuid(), nullable=False),
    sa.Column('symbol', sa.String(length=50), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=38, scale=18), nullable=False),
    sa.Column('cost_basis_usd', sa.Numeric(precision=20, scale=4), nullable=False),
    sa.Column('proceeds_usd', sa.Numeric(precision=20, scale=4), nullable=False),
    sa.Column('gain_usd', sa.Numeric(precision=20, scale=4), nullable=False),
    sa.Column('holding_days', sa.BigInteger(), nullable=False),
    sa.Column('buy_entry_id', sa.Uuid(), nullable=True),
    sa.Column('sell_entry_id', sa.Uuid(), nullable=True),
    sa.Column('buy_timestamp', sa.DateTime(), nullable=True),
    sa.Column('sell_timestamp', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['buy_entry_id'], ['journal_entries.id'], name=op.f('fk_closed_lots_buy_entry_id_journal_entries')),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], name=op.f('fk_closed_lots_entity_id_entities')),
    sa.ForeignKeyConstraint(['sell_entry_id'], ['journal_entries.id'], name=op.f('fk_closed_lots_sell_entry_id_journal_entries')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_closed_lots'))
    )
    op.create_table('open_lots',
    sa.Column('entity_id', sa.Uuid(), nullable=False),
    sa.Column('symbol', sa.String(length=50), nullable=False),
    sa.Column('remaining_quantity', sa.Numeric(precision=38, scale=18), nullable=False),
    sa.Column('cost_basis_per_unit_usd', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('buy_entry_id', sa.Uuid(), nullable=True),
    sa.Column('buy_timestamp', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['buy_entry_id'], ['journal_entries.id'], name=op.f('fk_open_lots_buy_entry_id_journal_entries')),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], name=op.f('fk_open_lots_entity_id_entities')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_open_lots'))
    )
    op.alter_column('accounts', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('accounts', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_accounts_label'), table_name='accounts')
    op.alter_column('entities', 'base_currency',
               existing_type=sa.VARCHAR(length=10),
               nullable=False,
               existing_server_default=sa.text("'VND'::character varying"))
    op.alter_column('entities', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('entities', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('journal_entries', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('journal_entries', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_journal_entries_entity_timestamp'), table_name='journal_entries')
    op.alter_column('journal_splits', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('journal_splits', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_journal_splits_account_id'), table_name='journal_splits')
    op.alter_column('parse_error_records', 'resolved',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('parse_error_records', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('parse_error_records', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_parse_error_records_error_type'), table_name='parse_error_records')
    op.alter_column('transactions', 'tx_hash',
               existing_type=sa.VARCHAR(length=66),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.alter_column('transactions', 'from_addr',
               existing_type=sa.VARCHAR(length=42),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.alter_column('transactions', 'to_addr',
               existing_type=sa.VARCHAR(length=42),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.alter_column('transactions', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'LOADED'::character varying"))
    op.alter_column('transactions', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('transactions', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_tx_hash'), table_name='transactions')
    op.create_index(op.f('ix_transactions_tx_hash'), 'transactions', ['tx_hash'], unique=False)
    op.add_column('wallets', sa.Column('exchange', sa.String(length=20), nullable=True))
    op.add_column('wallets', sa.Column('api_key_encrypted', sa.String(length=500), nullable=True))
    op.add_column('wallets', sa.Column('api_secret_encrypted', sa.String(length=500), nullable=True))
    op.add_column('wallets', sa.Column('last_trade_id', sa.String(length=100), nullable=True))
    op.alter_column('wallets', 'sync_status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'IDLE'::character varying"))
    op.alter_column('wallets', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('wallets', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_address'), table_name='wallets')
    op.create_index(op.f('ix_wallets_address'), 'wallets', ['address'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_wallets_address'), table_name='wallets')
    op.create_index(op.f('ix_address'), 'wallets', ['address'], unique=False)
    op.alter_column('wallets', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('wallets', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('wallets', 'sync_status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'IDLE'::character varying"))
    op.drop_column('wallets', 'last_trade_id')
    op.drop_column('wallets', 'api_secret_encrypted')
    op.drop_column('wallets', 'api_key_encrypted')
    op.drop_column('wallets', 'exchange')
    op.drop_index(op.f('ix_transactions_tx_hash'), table_name='transactions')
    op.create_index(op.f('ix_tx_hash'), 'transactions', ['tx_hash'], unique=False)
    op.alter_column('transactions', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('transactions', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('transactions', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'LOADED'::character varying"))
    op.alter_column('transactions', 'to_addr',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=42),
               existing_nullable=True)
    op.alter_column('transactions', 'from_addr',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=42),
               existing_nullable=True)
    op.alter_column('transactions', 'tx_hash',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=66),
               existing_nullable=False)
    op.create_index(op.f('ix_parse_error_records_error_type'), 'parse_error_records', ['error_type'], unique=False)
    op.alter_column('parse_error_records', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('parse_error_records', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('parse_error_records', 'resolved',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.create_index(op.f('ix_journal_splits_account_id'), 'journal_splits', ['account_id'], unique=False)
    op.alter_column('journal_splits', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('journal_splits', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_journal_entries_entity_timestamp'), 'journal_entries', ['entity_id', 'timestamp'], unique=False)
    op.alter_column('journal_entries', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('journal_entries', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('entities', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('entities', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('entities', 'base_currency',
               existing_type=sa.VARCHAR(length=10),
               nullable=True,
               existing_server_default=sa.text("'VND'::character varying"))
    op.create_index(op.f('ix_accounts_label'), 'accounts', ['label'], unique=True)
    op.alter_column('accounts', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('accounts', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_table('open_lots')
    op.drop_table('closed_lots')
    op.drop_table('reports')
    op.drop_index(op.f('ix_price_cache_timestamp'), table_name='price_cache')
    op.drop_index(op.f('ix_price_cache_symbol'), table_name='price_cache')
    op.drop_table('price_cache')
    # ### end Alembic commands ###
