"""phase12_taxable_transfers

Revision ID: 9d62205851e4
Revises: v3_001
Create Date: 2026-02-21 23:39:06.298843

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d62205851e4'
down_revision: Union[str, Sequence[str], None] = 'v3_001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('taxable_transfers',
    sa.Column('entity_id', sa.Uuid(), nullable=False),
    sa.Column('journal_entry_id', sa.Uuid(), nullable=False),
    sa.Column('symbol', sa.String(length=50), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=38, scale=18), nullable=False),
    sa.Column('value_usd', sa.Numeric(precision=20, scale=4), nullable=False),
    sa.Column('value_vnd', sa.Numeric(precision=24, scale=0), nullable=False),
    sa.Column('tax_amount_vnd', sa.Numeric(precision=24, scale=0), nullable=False),
    sa.Column('exemption_reason', sa.String(length=50), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], name=op.f('fk_taxable_transfers_entity_id_entities')),
    sa.ForeignKeyConstraint(['journal_entry_id'], ['journal_entries.id'], name=op.f('fk_taxable_transfers_journal_entry_id_journal_entries')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_taxable_transfers'))
    )
    op.create_index('ix_taxable_transfers_entity_id', 'taxable_transfers', ['entity_id'], unique=False)
    op.create_index('ix_taxable_transfers_symbol', 'taxable_transfers', ['symbol'], unique=False)
    op.create_index('ix_taxable_transfers_timestamp', 'taxable_transfers', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_taxable_transfers_timestamp', table_name='taxable_transfers')
    op.drop_index('ix_taxable_transfers_symbol', table_name='taxable_transfers')
    op.drop_index('ix_taxable_transfers_entity_id', table_name='taxable_transfers')
    op.drop_table('taxable_transfers')
    # ### end Alembic commands ###
